name: Ubuntu
on: push
jobs:
  release-test:
    name: dataflow build on ubuntu
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install deps
      run: (git clone --depth=1 -b v0.5.0 https://github.com/google/glog.git && cd glog && mkdir build && cd build && cmake .. && make -j8 && sudo make install)
    - name: lib version
      run: cd lib_version && bash -ex run.sh
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: .gitignore
